title: Guias SIMO Colombia
description: Información actualizada sobre convocatorias del sistema SIMO en Colombia
baseurl: ""
url: "https://guiasimo.com"
theme: null

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
